<select id="items">
	<option value="3D Printing">3D Printing</option>
	<option value="Alternative Currencies">Alternative Currencies</option>
	<option value="Big Data">Big Data</option>
	<option value="Big Data Social">Big Data Social</option>
	<option value="Bioethics">Bioethics</option>
	<option value="Biohacking">Biohacking</option>
	<option value="Biomimicry">Biomimicry</option>
	<option value="Black hat">Black hat</option>
	<option value="Boycott">Boycott</option>
	<option value="Brand Advocacy">Brand Advocacy</option>
	<option value="Branded Government">Branded Government</option>
	<option value="Buycott">Buycott</option>
	<option value="Changing Families">Changing Families</option>
	<option value="Community schooling">Community schooling</option>
	<option value="Coworking">Coworking</option>
	<option value="Crowdfunding">Crowdfunding</option>
	<option value="Crowdlearning">Crowdlearning</option>
	<option value="Cyber crimes">Cyber crimes</option>
	<option value="Cyberhacking">Cyberhacking</option>
	<option value="Cybersecurity">Cybersecurity</option>
	<option value="Deep Web">Deep Web</option>
	<option value="Digital Medicine">Digital Medicine</option>
	<option value="Digital Rights">Digital Rights</option>
	<option value="E-Gov">E-Gov</option>
	<option value="energy efficiency">energy efficiency</option>
	<option value="entrepreneurship">entrepreneurship</option>
	<option value="Experience learning">Experience learning</option>
	<option value="Food Science">Food Science</option>
	<option value="Foreign fusion">Foreign fusion</option>
	<option value="Gamification">Gamification</option>
	<option value="Good deeds">Good deeds</option>
	<option value="Green Revolution">Green Revolution</option>
	<option value="Hand made">Hand made</option>
	<option value="Holocracy">Holocracy</option>
	<option value="Homescooling">Homescooling</option>
	<option value="house automation">house automation</option>
	<option value="Internet of things">Internet of things</option>
	<option value="Intolerence">Intolerence</option>
	<option value="Jornalism3.0">Jornalism3.0</option>
	<option value="Learning Games">Learning Games</option>
	<option value="Mass customization">Mass customization</option>
	<option value="Millenium generation">Millenium generation</option>
	<option value="mobility">mobility</option>
	<option value="Nanotechnology">Nanotechnology</option>
	<option value="New political party">New political party</option>
	<option value="Nutrition">Nutrition</option>
	<option value="Omni Channel">Omni Channel</option>
	<option value="open source">open source</option>
	<option value="Plataformas integradas">Plataformas integradas</option>
	<option value="Political participation">Political participation</option>
	<option value="Political platforms">Political platforms</option>
	<option value="Prosumer">Prosumer</option>
	<option value="religious conflict">religious conflict</option>
	<option value="Robotics">Robotics</option>
	<option value="Self/Food Tracking">Self/Food Tracking</option>
	<option value="Sharing">Sharing</option>
	<option value="Smart cities">Smart cities</option>
	<option value="Social Impact">Social Impact</option>
	<option value="Social Investment Business">Social Investment Business</option>
	<option value="Star-up">Star-up</option>
	<option value="Third sector innovation">Third sector innovation</option>
	<option value="Unschooling">Unschooling</option>
	<option value="Urbaneering">Urbaneering</option>
</select>